sudo: required
services:
  - docker

before_install:
  - docker build --tag lbrady/docker-react -f Dockerfile.dev .

script:
  - docker container run lbrady/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
